### PR TITLE
fix: [#6697]Typing middleware not working as expected in teams as well as web chat channel

### PR DESCRIPTION
**Pull request by JhontSouth**
#minor

## Description
This PR allows showing the typing indicator before every message bot.

## Specific Changes
  - Added _**ProcessTypingAsync**_ method in _ShowTypingMiddleware_ class.
  - Added _StartTyping_ process to every activity iteration in the _OnSendActivities_ method execution.
 
## Testing
The following image shows the typing indicator being displayed between the different messages sent by the bot.
image

### CODE REVIEW

**Review by ceciliaavila — APPROVED** [review]
In the PR's description:
- Added StartTyping process? Wasn't this already part of the implementation? 
- After every message -> before every message

**Comment by JhontSouth** [comment]
> In the PR's description:
> 
> * Added StartTyping process? Wasn't this already part of the implementation?
> * After every message -> before every message

- The StartTyping process was not in the iteration, just the FinishTyping
image

**Comment by JhontSouth** [comment]
> In the PR's description:
> 
> * Added StartTyping process? Wasn't this already part of the implementation?
> * After every message -> before every message

- For the second point I am highlighting that it is still displayed after several bot messages and not only before the first message.

**Review by sw-joelmut — APPROVED** [review]

**Comment by JhontSouth** [comment]
Promoted /6743

**Pull request closed without merging**
