### PR TITLE
[TestBot] Consolidate duplicate Test project and test code

### PR DESCRIPTION
**Pull request by sw-joelmut**
Addresses # 4366

## Description
This PR consolidates duplicate code from `TestBot` and `TestBot.NetCore21` into a `TestBot.Shared` project.
To reduce code duplication `TestBot.NetCore21.Tests` was removed in favor of only having one `TestBot.Tests` test suite that decides to target either `NetCore 2.1` or `3.1`, as well as updating the reference to point to `TestBot.Shared` project instead of `TestBot` or `TestBot.NetCore21` projects.

## Specific Changes

  - Added `TestBot.Shared` project consolidating `TestBot` and `TestBot.NetCore21` projects.
  - Updated `TestBot, TestBot.NetCore21` and `TestBot.Tests` references to point to `TestBot.Shared` project.
  - Removed `TestBot.NetCore21.Tests` in favor of `TestBot.Tests`.

## Testing
In the following images there is a sneak peek about the passing tests, code coverage, structure of the `TestBot` project and the successfully ran pipelines for `dotnet-ci` and `dotnet-functional-tests`.
image

### CODE REVIEW

**Comment by santgr11** [comment]
Since the `TestBot.Tests` are now testing the files in `TestBot.Shared`, should we rename that project to `TestBot.Shared.Tests`?
Also, we should consider splitting the PR in two, one for the shared bot, one for the shared tests.
Someone else could bring their opinion on this?

**Comment by sw-joelmut** [comment]
> 
> 
> Since the `TestBot.Tests` are now testing the files in `TestBot.Shared`, should we rename that project to `TestBot.Shared.Tests`?
> Also, we should consider splitting the PR in two, one for the shared bot, one for the shared tests.
> Someone else could bring their opinion on this?
> 
> Also, we could add the impact in the code coverage in the testing images

The reason why I left the name of `TestBot` as is, is because of consistency with the others TestBot, It's true that is testing the Shared project but I estimate that should be called `TestBot` only.

Regarding the divide it in two PRs, I don't think we can, because the modified projects relates to the new Shared project.

**Review by ceciliaavila — APPROVED** [review]
Please add the coverage info as Santiago requested. The rest, LGTM

**Comment by sw-joelmut** [comment]
> 
> 
> Please add the coverage info as Santiago requested. The rest, LGTM

Updated the image including the code coverage, I had to add the coverage number from the pipeline 'cause I couldn't get it from the code.

**Comment by denscollo** [comment]
This PR is way too big to review, I'd have created a PR that removes the file, and another with the code changes because 87 files seems a lot at first sight

**Comment by denscollo** [comment]
Promoted

**Pull request closed without merging**
